appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Q+ZPRsiByRgLCcLIDCkwpk9Wjy5hICu8atT03QZmd57Q58q6k9KhjKFRHkd3ZOTGbtwAa/3Bq8cfCL+09nPpEPQ1PH1bHiRgzvRqdNtao4MP8HLuwNhHZDtKLT0yLpnMV40mKu2e8MW2ylP9M03N8qWQjFMfpMgK+IwXyqzoniVO6Z7xv9nkqc+DRO0hss4jKedXARpGO2n4uT6Nun95kJ8stXZYhGWRxa2Q8fl9AlIexkrOaQEXv8NEMyFy6uEtU0Se0Qz6o51KEDFXzkmX4rBHNC8mZRW/peaSIb1KiU3SrjR9GH/h/Dw96tE5yCTDbIQRpHg8Q4gqcUotCMqygOKJ5L6/oN3TD2bdfNjoIb1wKWKr/XRA44DB6CWZa41zU4DkXy7E/GliJ6FjIICLuMTJaHCy5x6TbKMRp4TW/+hwCTqvSMXJnfUAjxIej1a4MxDAcVWlCL3kWX0Easbp98144YmQ/oya4dcoi11Iwa0LtcEbU2oIioLgjbMBryLwdgI9pV2aJK32Zod/YEF1sSiU+ONFDrbNT5VOX/nki03jxh520qeRxj+RMBwnWuuRhAECW5onMaA+FDqyQYdTPN74YmDs7dEyBSP39Z5NT6W+fgztzUf39Z5jdDyRXL2GlGkljSvxy2YZFq3iEguI6m17XyKDglvFNLcu8eCoHcA=}
